name: ci

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os:
          - macos-latest
            #          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: install rust toolchain
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - name: test leaf
        run: cargo test -p leaf

  build-bin-local:
    strategy:
      matrix:
        os: [macos-latest]
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: show last commit
        run: |
          git show --summary

      - name: install rust toolchain
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - name: install llvm
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew install llvm protobuf

      - name: build
        run: |
          export CFG_COMMIT_HASH=`git log --pretty=format:'%h' -n 1`
          export CFG_COMMIT_DATE=`git log --format="%ci" -n 1`
          cargo build --release --target ${{ matrix.target }} -p leaf-bin

      - name: rename and compress artifacts
        run: |
          mv target/${{ matrix.target }}/release/leaf leaf-${{ matrix.target }}

      - name: upload assets
        uses: actions/upload-artifact@v4
        with:
          name: leaf-${{ matrix.target }}
          path: leaf-${{ matrix.target }}

  build-apple:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: install rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - name: install toolchain
        run: |
          cargo install cbindgen
          brew install llvm unzip protobuf

      - name: build
        run: |
          ./scripts/build_apple_xcframework.sh

      - name: zip artifacts
        run: |
          mv target/apple/release/leaf.xcframework .
          zip -r leaf.xcframework.zip leaf.xcframework

      - name: upload assets
        uses: actions/upload-artifact@v4
        with:
          name: leaf.xcframework.zip
          path: leaf.xcframework.zip
